[[micromamba]]
arch = "aarch64"
git-tree-sha1 = "48a5ddeef0d50b040156e9fae27b57ccd8d579e2"
os = "macos"

    [[micromamba.download]]
    sha256 = "6548aa294e9eb93ad9aab855345a3f6707f0a8dffbf1e0c539d40f8d449bfa69"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v0.25.1+0/micromamba.v0.25.1.aarch64-apple-darwin.tar.gz"
[[micromamba]]
arch = "aarch64"
git-tree-sha1 = "2e4d783c337fe9077d683ac240f10e2607bc1599"
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "7e02becb3688a4d3995e616d3a9a907498f9527627f61893b7f0a348b4a0da06"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v0.25.1+0/micromamba.v0.25.1.aarch64-linux-gnu.tar.gz"
[[micromamba]]
arch = "powerpc64le"
git-tree-sha1 = "2e8fb274dc2b358c2d5613bc8cfd17156a630fb6"
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "22b116d9c28675af17f382b7b64a1dc9cdb97a1d4c816095123d892b1bcc1ae9"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v0.25.1+0/micromamba.v0.25.1.powerpc64le-linux-gnu.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "13622804caf56b74f853b2728ea534d3d4acf0c1"
os = "macos"

    [[micromamba.download]]
    sha256 = "0d066844316cc0c0ad1f1485a9e73ac90fc6e5da083ac7640d5530183097c6df"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v0.25.1+0/micromamba.v0.25.1.x86_64-apple-darwin.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "8d5103d84a46e89c60d007a7d30b926037514616"
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "9102b1d4d1f15762f53f171a8f41223603d33638187c424f0cfb0f9900d435fb"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v0.25.1+0/micromamba.v0.25.1.x86_64-linux-gnu.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "e1a576633d6fe07d116d2b5534fb512bce3eaa47"
os = "windows"

    [[micromamba.download]]
    sha256 = "682b0ccea4bbdb6ce0977bfd7004a2e4647b720b29cd13b3dfd7f13b310f6256"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v0.25.1+0/micromamba.v0.25.1.x86_64-w64-mingw32.tar.gz"
