[[micromamba]]
arch = "aarch64"
git-tree-sha1 = "7cfea9db5b54ceb7d9109c8728914c9459303a75"
lazy = true
os = "macos"

    [[micromamba.download]]
    sha256 = "cc2565055c76ce2d8fd705d811e2db1dfd2ae41ca93a88e8cd914bfb5bf06359"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.4.1+0/micromamba.v1.4.1.aarch64-apple-darwin.tar.gz"
[[micromamba]]
arch = "aarch64"
git-tree-sha1 = "5fde96ed453da643ca123e6e974dca0dece6224a"
lazy = true
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "4ddc8e49b7c32f09b39cbbf7e3d8245fcf7098d605f65c2a316f1283f31ea688"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.4.1+0/micromamba.v1.4.1.aarch64-linux-gnu.tar.gz"
[[micromamba]]
arch = "powerpc64le"
git-tree-sha1 = "e1db64959b1dd25ea6b2f09ac8534fddb160bcdd"
lazy = true
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "6dace599452878d79170c1ff7b30ec4306f91e1240e4b0fe3c4d6d89d025db45"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.4.1+0/micromamba.v1.4.1.powerpc64le-linux-gnu.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "523ed46aaf6a8679b4a8af4116a856ed63259b37"
lazy = true
os = "macos"

    [[micromamba.download]]
    sha256 = "7346d9c53b24f51df42491718fef2ba027d783c4186f84065c2e0c810dde2894"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.4.1+0/micromamba.v1.4.1.x86_64-apple-darwin.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "a7fe6379eb776b1ec5b4ee1ddb8da76446d3f735"
lazy = true
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "7a064245e7819523e54ffc7286f53cdbf5751c00087449cff95008d4dd1a03ab"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.4.1+0/micromamba.v1.4.1.x86_64-linux-gnu.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "444cdd4c5cbacc31e39255b42de7eb3458f5ebd1"
lazy = true
os = "windows"

    [[micromamba.download]]
    sha256 = "78a6b482b6330433f30c239d5ae1a7a6fca63fdc103c660ebdc60e23143f1a64"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.4.1+0/micromamba.v1.4.1.x86_64-w64-mingw32.tar.gz"
