[[micromamba]]
arch = "aarch64"
git-tree-sha1 = "abbaad6c2d5e2bba20b0dd646a576cc0a5d70979"
lazy = true
os = "macos"

    [[micromamba.download]]
    sha256 = "942be4991fab59a80037e2a5b5d02edee5c986b99117b9e603c769eb590047fc"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.2.0+0/micromamba.v1.2.0.aarch64-apple-darwin.tar.gz"
[[micromamba]]
arch = "aarch64"
git-tree-sha1 = "076363e81feec3c7259a8af26f1a5f7f117652ed"
lazy = true
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "3ffe63ddbac46e7c6850bda7855481c1d8de981dc19dd9126220f368785b2589"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.2.0+0/micromamba.v1.2.0.aarch64-linux-gnu.tar.gz"
[[micromamba]]
arch = "powerpc64le"
git-tree-sha1 = "9941b926436a4559726cbe802e7a3d58f55fca33"
lazy = true
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "047c0f32f4c623e7dcb267b61bdb68df091740941bca72b65068e89ad83a06c2"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.2.0+0/micromamba.v1.2.0.powerpc64le-linux-gnu.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "41ce90f9524fa87b3c2b8632eb6d1eb4264dfa43"
lazy = true
os = "macos"

    [[micromamba.download]]
    sha256 = "6ac74b4a4f840caa0680f687277fceb534af18fe64bdb65121f3f7b1c517d128"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.2.0+0/micromamba.v1.2.0.x86_64-apple-darwin.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "0f94204b5ccc382e173f9e6d035af169744cf40d"
lazy = true
libc = "glibc"
os = "linux"

    [[micromamba.download]]
    sha256 = "75f0dfd5aaa9b926999297451e1924f4ca30a4712ead256bd87eef6822dabb61"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.2.0+0/micromamba.v1.2.0.x86_64-linux-gnu.tar.gz"
[[micromamba]]
arch = "x86_64"
git-tree-sha1 = "4b82d7ce236527959584cbf6b4cd3a10545b99ac"
lazy = true
os = "windows"

    [[micromamba.download]]
    sha256 = "a12cd7de2ffb4bb5090ad6e1e1ae94e260e10f826ce2a4f83a12dbf179b84e31"
    url = "https://github.com/JuliaBinaryWrappers/micromamba_jll.jl/releases/download/micromamba-v1.2.0+0/micromamba.v1.2.0.x86_64-w64-mingw32.tar.gz"
