# Autogenerated wrapper script for micromamba_jll for x86_64-w64-mingw32
export micromamba

JLLWrappers.@generate_wrapper_header("micromamba")
JLLWrappers.@declare_executable_product(micromamba)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        micromamba,
        "bin\\micromamba.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
